import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "../styles.css";

const apiBase = window.VPN_API_BASE_URL || "/api/v1";
const providerNames = { crypto_pay: "Crypto Pay", anore: "Anore", telegram_stars: "Telegram Stars" };
const money = (value, currency = "RUB") => new Intl.NumberFormat("ru-RU", { style: "currency", currency, maximumFractionDigits: currency === "XTR" ? 0 : 2 }).format((value || 0) / (currency === "XTR" ? 1 : 100));
const date = (value) => value ? new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "-";
const label = (value) => ({ paid: "оплачен", pending: "ожидает", active: "активна", provisioning_pending: "в обработке", expired: "истекла", suspended: "приостановлена", failed: "ошибка", wallet_top_up: "пополнение", direct_purchase: "покупка", balance: "баланс", discount: "скидка" }[value] || String(value || "").replaceAll("_", " "));
const initialTariff = { code: "", name: "", description: "", duration_days: "30", traffic_gb: "", position: "0", amount_rub: "", currency_code: "RUB", is_active: true };
const initialPromo = { code: "", kind: "discount", amount_rub: "", discount_percent: "", maximum_redemptions: "", is_active: true };
const initialChannel = { telegram_chat_id: "", title: "", public_url: "", is_active: true };

function App() {
  const [token, setToken] = useState(null); const [data, setData] = useState(null); const [tab, setTab] = useState("overview");
  const [setupRequired, setSetupRequired] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const request = async (path, options = {}, session = token) => {
    const response = await fetch(`${apiBase}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(session ? { Authorization: `Bearer ${session}` } : {}), ...options.headers } });
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).message || "Не удалось выполнить запрос");
    return response.status === 204 ? null : response.json();
  };
  const load = async (session) => {
    const get = (path) => request(path, {}, session);
    const [dashboard, analytics, settings, referralSettings, providers, publicSettings, runtimeSettings, telegramTransport, tariffs, channels, promos, users, subscriptions, invoices, audit] = await Promise.all([
      get("/admin/dashboard"), get("/admin/analytics"), get("/admin/trial-settings"), get("/admin/referral-settings"), get("/admin/payment-providers"), get("/admin/public-settings"), get("/admin/runtime-settings"), get("/admin/telegram-transport"), get("/admin/tariffs"), get("/admin/required-channels"), get("/admin/promos"), get("/admin/users?limit=50&offset=0"), get("/admin/subscriptions?limit=50&offset=0"), get("/admin/invoices?limit=50&offset=0"), get("/admin/audit?limit=50&offset=0")
    ]);
    setData({ dashboard, analytics, settings, referralSettings, providers, publicSettings, runtimeSettings, telegramTransport, tariffs, channels, promos, users, subscriptions, invoices, audit });
  };
  const bootstrap = async () => { setLoading(true); setError(""); try { const saved = JSON.parse(sessionStorage.getItem("vpn-admin-session") || "null"); if (saved?.token && saved.expiresAt > Date.now()) { setToken(saved.token); await load(saved.token); } else { setSetupRequired((await request("/admin/setup-status")).setup_required); } } catch (cause) { setError(cause.message); } finally { setLoading(false); } };
  useEffect(() => { bootstrap(); }, []);
  const authenticate = async ({ login, password }) => { setLoading(true); setError(""); try { const auth = await request(setupRequired ? "/admin/setup" : "/admin/login", { method: "POST", body: JSON.stringify({ login, password }) }, null); sessionStorage.setItem("vpn-admin-session", JSON.stringify({ token: auth.access_token, expiresAt: new Date(auth.expires_at).getTime() })); setToken(auth.access_token); await load(auth.access_token); } catch (cause) { setError(cause.message); } finally { setLoading(false); } };
  const mutate = async (path, method, body, message) => { try { await request(path, { method, body: JSON.stringify(body) }); setNotice(message); await load(token); } catch (cause) { setNotice(cause.message); } };
  if (loading) return <State title="Загружаем панель управления" />;
  if (!token) return <AdminLogin setupRequired={setupRequired} error={error} onSubmit={authenticate} />;
  if (error) return <State title="Нет доступа к панели" detail={error} action={bootstrap} />;
  const pages = {
    overview: <Overview dashboard={data.dashboard} analytics={data.analytics} />,
    users: <Users data={data.users} onCreate={(body) => mutate("/admin/users", "POST", body, "Клиент создан.")} />,
    payments: <Invoices data={data.invoices} />,
    subscriptions: <Subscriptions data={data.subscriptions} />,
    tariffs: <Tariffs items={data.tariffs} onSave={(body, id) => mutate(`/admin/tariffs${id ? `/${id}` : ""}`, id ? "PUT" : "POST", body, id ? "Тариф обновлен." : "Тариф создан.")} />,
    promos: <Promos items={data.promos} onSave={(body, id) => mutate(`/admin/promos${id ? `/${id}` : ""}`, id ? "PUT" : "POST", body, id ? "Промокод обновлен." : "Промокод создан.")} />,
    channels: <Channels items={data.channels} onSave={(body, id) => mutate(`/admin/required-channels${id ? `/${id}` : ""}`, id ? "PUT" : "POST", body, id ? "Канал обновлен." : "Канал добавлен.")} />,
    integrations: <Integrations items={data.providers} onToggle={(item) => mutate(`/admin/payment-providers/${item.provider_code}`, "PUT", { is_enabled: !item.is_enabled }, item.is_enabled ? "Провайдер выключен." : "Провайдер включен.")} />,
    policies: <Policies settings={data.settings} referrals={data.referralSettings} onSave={(path, body, message) => mutate(path, "PUT", body, message)} />,
    runtime: <Runtime data={data} onSave={(path, body, message) => mutate(path, "PUT", body, message)} />,
    audit: <Audit data={data.audit} />
  };
  return <><header className="topbar"><button className="brand" onClick={() => setTab("overview")}><b /> VPN // OPS <span>ПАНЕЛЬ УПРАВЛЕНИЯ</span></button><div className="top-actions"><span className="live"><i />СЕССИЯ ПОДТВЕРЖДЕНА</span><button className="text-button" onClick={() => { sessionStorage.removeItem("vpn-admin-session"); setToken(null); setData(null); bootstrap(); }}>Выйти</button></div></header><div className="admin-shell"><Nav tab={tab} setTab={setTab} /><main className="content">{notice && <button className="notice" onClick={() => setNotice("")}>{notice}<span>×</span></button>}{pages[tab]}</main></div></>;
}

function AdminLogin({ setupRequired, error, onSubmit }) { const [login, setLogin] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [localError, setLocalError] = useState(""); const submit = (event) => { event.preventDefault(); if (setupRequired && password !== confirm) return setLocalError("Пароли не совпадают."); onSubmit({ login, password }); }; return <main className="login-shell"><section className="login-card"><p className="eyebrow">VPN // CONTROL PLANE</p><h1>{setupRequired ? "Создание главного администратора" : "Вход администратора"}</h1><p className="helper">{setupRequired ? "Эта учетная запись управляет доступом в панель." : "Используйте логин и пароль администратора."}</p><form onSubmit={submit}><label>Логин<input value={login} autoComplete="username" minLength="3" onChange={(event) => setLogin(event.target.value)} required /></label><label>Пароль<input value={password} type="password" autoComplete="current-password" minLength="12" onChange={(event) => setPassword(event.target.value)} required /></label>{setupRequired && <label>Повторите пароль<input value={confirm} type="password" minLength="12" onChange={(event) => setConfirm(event.target.value)} required /></label>}<button type="submit">{setupRequired ? "Создать администратора" : "Войти"}</button></form>{(localError || error) && <p className="login-error">{localError || error}</p>}</section></main>; }
function Nav({ tab, setTab }) { const groups = [["ГЛАВНОЕ", [["overview", "Обзор"], ["users", "Клиенты"]]], ["ОПЕРАЦИИ", [["payments", "Платежи"], ["subscriptions", "Подписки"], ["tariffs", "Тарифы"], ["promos", "Промокоды"]]], ["ДОСТУП", [["channels", "Обязательные каналы"], ["integrations", "Платежные системы"]]], ["НАСТРОЙКИ", [["policies", "Правила"], ["runtime", "Среда"], ["audit", "Журнал аудита"]]]]; return <aside className="sidebar">{groups.map(([name, items]) => <section className="nav-group" key={name}><small>{name}</small>{items.map(([id, title]) => <button className={`nav-item ${tab === id ? "active" : ""}`} onClick={() => setTab(id)} key={id}>{title}</button>)}</section>)}<div className="sidebar-foot">ADMIN / V2<br />АУДИТИРУЕМЫЕ ОПЕРАЦИИ</div></aside>; }
function Heading({ kicker, title, description, children }) { return <section className="section-head"><div><p>{kicker}</p><h1>{title}</h1><span>{description}</span></div>{children}</section>; }
function State({ title, detail, action }) { return <main className="state"><i /><h1>{title}</h1>{detail && <p>{detail}</p>}{action && <button onClick={action}>Повторить</button>}</main>; }
function Overview({ dashboard, analytics }) { return <><Heading kicker="ГЛАВНОЕ / ОБЗОР" title="Операционный центр" description="Ключевые показатели, денежный поток и регистрация клиентов." /><section className="metric-grid"><Metric label="Клиенты" value={dashboard.registered_users} /><Metric label="Активные подписки" value={dashboard.active_subscriptions} /><Metric label="Оплаченные счета" value={dashboard.paid_invoices} /><Metric label="Выручка" value={money(dashboard.paid_revenue_rub_minor)} /></section><section className="chart-grid"><Chart title="Регистрации за 14 дней" points={analytics.registrations} /><Chart title="Выручка за 14 дней" points={analytics.revenue_rub_minor} format={(value) => money(value)} /></section><section className="split-grid"><article className="panel"><div className="panel-title"><div><p>ОЧЕРЕДЬ ОПЕРАТОРА</p><h2>Требует внимания</h2></div></div><Row title="Ожидают оплаты" value={dashboard.pending_invoices} /><Row title="Ожидают выдачи доступа" value={dashboard.provisioning_pending_subscriptions} /></article><article className="panel"><p>ГРАНИЦА УПРАВЛЕНИЯ</p><h2>Прокси остается на хосте</h2><p className="helper">Домены, nginx и TLS управляются вручную на сервере. В панели редактируются только настройки приложения.</p></article></section></>; }
function Metric({ label, value }) { return <article className="metric"><span>{label}</span><strong>{value}</strong><small>Текущее значение</small></article>; }
function Row({ title, value }) { return <div className="signal-row"><span>{title}</span><b>{value}</b></div>; }
function Chart({ title, points, format = (value) => value }) { const max = Math.max(1, ...points.map((point) => Number(point.value))); return <article className="chart"><div className="panel-title"><div><p>АНАЛИТИКА</p><h2>{title}</h2></div><b>{format(points.reduce((sum, point) => sum + Number(point.value), 0))}</b></div><div className="bar-chart">{points.map((point) => <div key={point.day} title={`${point.day}: ${format(point.value)}`}><i style={{ height: `${Math.max(3, Number(point.value) / max * 100)}%` }} /><small>{point.day.slice(5)}</small></div>)}</div></article>; }
function Users({ data, onCreate }) { const [form, setForm] = useState({ telegram_user_id: "", username: "", first_name: "", language_code: "ru" }); const submit = (event) => { event.preventDefault(); onCreate({ ...form, telegram_user_id: Number(form.telegram_user_id), username: form.username.replace(/^@/, "") || null }); setForm({ telegram_user_id: "", username: "", first_name: "", language_code: "ru" }); }; return <><Heading kicker="ГЛАВНОЕ / КЛИЕНТЫ" title="Клиенты" description="Клиенты обычно появляются после первого входа через Telegram. Здесь можно добавить клиента вручную." /><section className="create-card"><h2>Добавить клиента</h2><form className="inline-form" onSubmit={submit}><input required inputMode="numeric" placeholder="Telegram ID" value={form.telegram_user_id} onChange={(event) => setForm({ ...form, telegram_user_id: event.target.value })} /><input placeholder="username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><input required placeholder="Имя клиента" value={form.first_name} onChange={(event) => setForm({ ...form, first_name: event.target.value })} /><select value={form.language_code} onChange={(event) => setForm({ ...form, language_code: event.target.value })}><option value="ru">Русский</option><option value="en">English</option></select><button>Создать клиента</button></form></section><section className="card-grid">{data.items.length ? data.items.map((item) => <article className="user-card" key={item.id}><div><span className="avatar">{(item.first_name || "?")[0]}</span><span><strong>{item.username ? `@${item.username}` : item.first_name}</strong><small>Telegram ID: {item.telegram_user_id}</small></span></div><b className="badge">{item.language_code}</b><div className="card-stats"><span><small>Баланс</small><b>{money(item.balance_minor, item.currency_code)}</b></span><span><small>Создан</small><b>{date(item.created_at)}</b></span></div></article>) : <Empty text="Клиентов пока нет." />}</section><Pager data={data} /></>; }
function Invoices({ data }) { return <><Heading kicker="ОПЕРАЦИИ / ПЛАТЕЖИ" title="Платежи" description="Состояния счетов и история платежных провайдеров." /><DataList data={data} render={(item) => <><div><p>{providerNames[item.provider] || label(item.provider)}</p><h2>{money(item.amount_minor, item.currency_code)}</h2><small>{label(item.purpose)} · {date(item.created_at)} · {item.username ? `@${item.username}` : `Telegram ${item.telegram_user_id}`}</small></div><b className={`badge ${item.status === "paid" ? "ok" : "warn"}`}>{label(item.status)}</b></>} /></>; }
function Subscriptions({ data }) { return <><Heading kicker="ОПЕРАЦИИ / ДОСТУП" title="Подписки" description="Жизненный цикл доступа и состояние выдачи конфигурации." /><DataList data={data} render={(item) => <><div><p>{item.tariff_code || "Пробный доступ"}</p><h2>{item.username ? `@${item.username}` : `Telegram ${item.telegram_user_id}`}</h2><small>Действует до: {date(item.expires_at)}</small></div><b className={`badge ${item.status === "active" ? "ok" : "warn"}`}>{label(item.status)}</b></>} /></>; }
function Tariffs({ items, onSave }) { const encode = (form) => ({ code: form.code, name: { ru: form.name }, description: { ru: form.description }, duration_seconds: Number(form.duration_days) * 86400 || null, traffic_bytes: form.traffic_gb === "" ? null : Number(form.traffic_gb) * 1024 ** 3, position: Number(form.position || 0), is_active: form.is_active, amount_minor: Math.round(Number(form.amount_rub || 0) * 100), currency_code: form.currency_code }); const decode = (item) => ({ code: item.code, name: item.name?.ru || "", description: item.description?.ru || "", duration_days: item.duration_seconds ? item.duration_seconds / 86400 : "", traffic_gb: item.traffic_bytes == null ? "" : item.traffic_bytes / 1024 ** 3, position: item.position, amount_rub: item.amount_minor / 100, currency_code: item.currency_code, is_active: item.is_active }); return <ResourcePage kicker="ОПЕРАЦИИ / КАТАЛОГ" title="Тарифы" description="Создание и редактирование предложений для Mini App." items={items} initial={initialTariff} decode={decode} onSave={(form, id) => onSave(encode(form), id)} fields={[['code', 'Код тарифа'], ['name', 'Название'], ['description', 'Описание'], ['duration_days', 'Срок, дней', 'number'], ['traffic_gb', 'Трафик, ГБ', 'number'], ['amount_rub', 'Цена, ₽', 'number'], ['position', 'Позиция', 'number'], ['currency_code', 'Валюта']] } render={(item) => <><div><p>{item.code}</p><h2>{item.name?.ru || item.code}</h2><small>{money(item.amount_minor, item.currency_code)} · {item.duration_seconds ? `${item.duration_seconds / 86400} дн.` : "без срока"} · {item.traffic_bytes == null ? "без лимита" : `${Math.round(item.traffic_bytes / 1024 ** 3)} ГБ`}</small></div><b className={`badge ${item.is_active ? "ok" : "warn"}`}>{item.is_active ? "активен" : "выключен"}</b></>} />; }
function Promos({ items, onSave }) { const encode = (form) => ({ code: form.code.toUpperCase(), kind: form.kind, amount_minor: form.kind === "balance" ? Math.round(Number(form.amount_rub || 0) * 100) : null, discount_percent: form.kind === "discount" ? Number(form.discount_percent) : null, maximum_redemptions: form.maximum_redemptions === "" ? null : Number(form.maximum_redemptions), is_active: form.is_active, starts_at: null, ends_at: null }); const decode = (item) => ({ code: item.code, kind: item.kind, amount_rub: item.amount_minor ? item.amount_minor / 100 : "", discount_percent: item.discount_percent ?? "", maximum_redemptions: item.maximum_redemptions ?? "", is_active: item.is_active }); return <ResourcePage kicker="ОПЕРАЦИИ / МАРКЕТИНГ" title="Промокоды" description="Фиксированные начисления или скидки на оплату." items={items} initial={initialPromo} decode={decode} onSave={(form, id) => onSave(encode(form), id)} fields={[['code', 'Код'], ['kind', 'Тип', 'select', [['discount', 'Скидка'], ['balance', 'Баланс']],], ['discount_percent', 'Скидка, %', 'number'], ['amount_rub', 'Начисление, ₽', 'number'], ['maximum_redemptions', 'Лимит активаций', 'number']]} render={(item) => <><div><p>{label(item.kind)}</p><h2>{item.code}</h2><small>{item.kind === "balance" ? money(item.amount_minor) : `${item.discount_percent}% скидка`} · использовано {item.redeemed_count}/{item.maximum_redemptions || "∞"}</small></div><b className={`badge ${item.is_active ? "ok" : "warn"}`}>{item.is_active ? "активен" : "выключен"}</b></>} />; }
function Channels({ items, onSave }) { const encode = (form) => ({ ...form, telegram_chat_id: Number(form.telegram_chat_id), public_url: form.public_url || null }); return <ResourcePage kicker="ДОСТУП / TELEGRAM" title="Обязательные каналы" description="Без подписки на активные каналы клиент не получит доступ к коммерческим действиям." items={items} initial={initialChannel} decode={(item) => ({ telegram_chat_id: item.telegram_chat_id, title: item.title, public_url: item.public_url || "", is_active: item.is_active })} onSave={(form, id) => onSave(encode(form), id)} fields={[['telegram_chat_id', 'Telegram chat ID', 'number'], ['title', 'Название'], ['public_url', 'Ссылка t.me']]} render={(item) => <><div><p>TELEGRAM</p><h2>{item.title}</h2><small>{item.telegram_chat_id}{item.public_url ? ` · ${item.public_url}` : ""}</small></div><b className={`badge ${item.is_active ? "ok" : "warn"}`}>{item.is_active ? "активен" : "выключен"}</b></>} />; }
function ResourcePage({ kicker, title, description, items, initial, decode, onSave, fields, render }) { const [form, setForm] = useState(initial); const [editing, setEditing] = useState(null); const submit = (event) => { event.preventDefault(); onSave(form, editing?.id); setForm(initial); setEditing(null); }; const edit = (item) => { setEditing(item); setForm(decode(item)); window.scrollTo({ top: 0, behavior: "smooth" }); }; return <><Heading kicker={kicker} title={title} description={description} /><section className="create-card"><div className="form-title"><h2>{editing ? "Редактирование" : "Создание"}</h2>{editing && <button className="secondary" type="button" onClick={() => { setEditing(null); setForm(initial); }}>Отменить</button>}</div><form className="inline-form resource-form" onSubmit={submit}>{fields.map(([key, title, type = "text", options]) => <label key={key}>{title}{type === "select" ? <select value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })}>{options.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select> : <input type={type} required={key === "code" || key === "title" || key === "name"} value={form[key] ?? ""} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />}</label>)}<label className="check"><input type="checkbox" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} />Активен</label><button>{editing ? "Сохранить" : "Создать"}</button></form></section><section className="data-list">{items.length ? items.map((item) => <article className="data-card editable" key={item.id} onClick={() => edit(item)}>{render(item)}<button className="secondary edit-button" onClick={(event) => { event.stopPropagation(); edit(item); }}>Изменить</button></article>) : <Empty text="Пока ничего не создано." />}</section></>; }
function Integrations({ items, onToggle }) { return <><Heading kicker="ДОСТУП / ПЛАТЕЖИ" title="Платежные системы" description="Включайте только настроенные провайдеры с заданными секретами." /><section className="provider-grid">{items.map((item) => <article className="provider-card" key={item.provider_code}><div><p>{providerNames[item.provider_code] || item.provider_code}</p><h2>{item.is_enabled ? "Включен" : "Выключен"}</h2><small>{item.is_configured ? "Учетные данные настроены" : "Не настроен"}</small></div><button className={item.is_enabled ? "secondary" : ""} disabled={!item.is_configured} onClick={() => onToggle(item)}>{item.is_enabled ? "Выключить" : "Включить"}</button></article>)}</section></>; }
function Policies({ settings, referrals, onSave }) { return <><Heading kicker="НАСТРОЙКИ / КОММЕРЦИЯ" title="Правила" description="Значения применяются к новым сценариям покупки и пробного доступа." /><section className="two-panel"><SettingsForm title="Пробный доступ" value={{ duration_days: settings.duration_seconds / 86400, traffic_gb: settings.traffic_bytes / 1024 ** 3 }} fields={["duration_days", "traffic_gb"]} labels={{ duration_days: "Срок, дней", traffic_gb: "Трафик, ГБ" }} onSave={(value) => onSave("/admin/trial-settings", { duration_seconds: Number(value.duration_days) * 86400, traffic_bytes: Number(value.traffic_gb) * 1024 ** 3 }, "Настройки пробного доступа сохранены.")} /><SettingsForm title="Реферальная программа" value={referrals} fields={["percent"]} labels={{ percent: "Вознаграждение, %" }} onSave={(value) => onSave("/admin/referral-settings", { percent: Number(value.percent) }, "Реферальное правило сохранено.")} /></section></>; }
function Runtime({ data, onSave }) { return <><Heading kicker="НАСТРОЙКИ / СРЕДА" title="Публичные адреса и транспорт" description="Nginx, DNS и TLS остаются под ручным управлением на хосте." /><section className="two-panel"><SettingsForm title="Публичные адреса" value={{ ...data.publicSettings, cors_origins: data.publicSettings.cors_origins.join(", ") }} fields={["mini_app_url", "admin_url", "subscription_public_url", "telegram_webhook_url", "cors_origins", "support_url"]} labels={{ mini_app_url: "Mini App URL", admin_url: "Админка URL", subscription_public_url: "URL подписки", telegram_webhook_url: "Webhook Telegram", cors_origins: "CORS origins", support_url: "Поддержка" }} onSave={(value) => onSave("/admin/public-settings", { ...value, cors_origins: value.cors_origins.split(",").map((item) => item.trim()).filter(Boolean), support_url: value.support_url || null }, "Публичные адреса сохранены.")} /><SettingsForm title="Локальные порты" value={data.runtimeSettings} fields={["api_host_port", "mini_app_host_port", "admin_host_port", "telegram_webhook_host_port"]} labels={{ api_host_port: "API", mini_app_host_port: "Mini App", admin_host_port: "Админка", telegram_webhook_host_port: "Telegram webhook" }} onSave={(value) => onSave("/admin/runtime-settings", numberFields(value), "План портов сохранен. Перезапустите Compose и обновите nginx.")} /></section><section className="two-panel"><SettingsForm title="Транспорт Telegram" value={data.telegramTransport} fields={["mode"]} options={{ mode: [["polling", "Polling"], ["webhook", "Webhook"]] }} labels={{ mode: "Режим" }} onSave={(value) => onSave("/admin/telegram-transport", value, "Транспорт Telegram сохранен. Перезапустите бота.")} /><article className="panel"><p>ГРАНИЦА ХОСТА</p><h2>Reverse proxy вне приложения</h2><p className="helper">Панель хранит URL и рекомендуемые порты, но не изменяет конфигурацию nginx, сертификаты или DNS.</p></article></section></>; }
function SettingsForm({ title, value, fields, labels = {}, options, onSave }) { const [form, setForm] = useState(value); useEffect(() => setForm(value), [value]); return <form className="form-card" onSubmit={(event) => { event.preventDefault(); onSave(form); }}><div className="form-head"><div><p>КОНФИГУРАЦИЯ</p><h2>{title}</h2></div></div>{fields.map((field) => <label key={field}>{labels[field] || field}{options?.[field] ? <select value={form[field] || ""} onChange={(event) => setForm({ ...form, [field]: event.target.value })}>{options[field].map(([value, title]) => <option key={value} value={value}>{title}</option>)}</select> : <input value={form[field] ?? ""} onChange={(event) => setForm({ ...form, [field]: event.target.value })} />}</label>)}<div className="form-actions"><button>Сохранить</button></div></form>; }
function Audit({ data }) { return <><Heading kicker="НАСТРОЙКИ / АУДИТ" title="Журнал аудита" description="Последние привилегированные изменения в панели управления." /><DataList data={data} render={(item) => <><div><p>{item.target_type}</p><h2>{item.action}</h2><small>{date(item.created_at)}</small></div><b className="badge">{item.actor_user_id ? "админ" : "система"}</b></>} /></>; }
function DataList({ data, render }) { return <><section className="data-list">{data.items.length ? data.items.map((item) => <article className="data-card" key={item.id}>{render(item)}</article>) : <Empty text="Нет записей." />}</section><Pager data={data} /></>; }
function Empty({ text }) { return <p className="empty">{text}</p>; }
function Pager({ data }) { return <div className="pager"><span>{data.total ? `${data.offset + 1}-${Math.min(data.offset + data.limit, data.total)} из ${data.total}` : "0 записей"}</span></div>; }
const numberFields = (value) => Object.fromEntries(Object.entries(value).map(([key, item]) => [key, /^\d+$/.test(String(item)) ? Number(item) : item]));
createRoot(document.getElementById("app")).render(<StrictMode><App /></StrictMode>);
